import React from 'react'

const PrivacyPolicy = () => {
    return (
        <div>
            <div class="contained">
                <h1><span>Privacy Policy</span></h1>
                <p><span>This Privacy Policy describes how Atricent handles your personal information and sets out the rights and obligations that both you and Atricent have in relation to your personal information.</span></p>
                <p><span>By accessing www.Atricent.com (the "Site") you accept and agree to the terms and conditions of Atricent&rsquo;s user agreement ("User Agreement"), which includes your consent to, and authorization of, the collection, use and disclosure of your personal information in accordance with this Privacy Policy. Note that under Atricent's terms and conditions of use, you must not use the Site if you are under 18 years old.</span></p>
                <h3><span>1. Collection and Use of Your Personal Information</span></h3>
                <p><span>Atricent provides a unique, innovative, community-based online outsourcing service. A failure by you to provide information requested by us may mean that We are unable to provide some or all of our services to you.</span></p>
                <p><span>Atricent collects personal information when you register with and use Atricent. This may include, but is not limited to, your name, address, phone number, contact details, birth date, gender, credit card and account details, occupation, interests, and application details for verification services. We might also give you the option of providing a photo or video to be associated with your Atricent user ID. If your personal details change, it is your responsibility to update your Atricent account with those changes, so that We can keep our records complete, accurate and up to date.</span></p>
                <p><span>You are not anonymous to us when you log into the Site or post any content (including bookings, items to be supplied, bids, comments or feedback) on the Site or any associated forum. To enable us to improve our existing services and to create new service features, Atricent may collect, and share with other users and service providers on Atricent, information about the way you use our services, including (but not limited to) the transactions you enter into on the Site, your feedback rating (including any references requested using our 'Reference' feature), the bids you make, the comments you post, and the transactions you enter into with our valued affiliate service providers.</span></p>
                <p><span>When you:</span></p>
                <ul>
                    <li>use the Site to post a bookings or item to be supplied, or make a bid, or comment on a bid, or provide feedback on other users; or</li>
                    <li>otherwise communicate in a public forum on the Site,</li>
                </ul>
                <p><span>your user ID and all the material that you post is visible to other Atricent users and is also publicly available to other internet users. We strongly encourage you to use caution and discretion when posting. Atricent does not in any way control, and does not accept any responsibility or liability whatsoever for, the disclosure or use of personal information which is voluntarily posted by you in any publicly accessible area of the Site.</span></p>
                <p><span>Atricent may also receive and record information from your internet browser and computer, including IP addresses, cookies (see section 2 below), software and hardware attributes and your page requests.</span></p>
                <p><span>In addition to data collected from your submissions, we may also collect data on your internet behavior from Facebook, other social media sites, and other services. If you use a location- enabled Atricent service, We may collect and process information about your actual location (for example, GPS signals sent by your mobile device). We may also use a range of different technologies to confirm your location.</span></p>
                <p><span>Atricent may use the information collected by it to provide the Atricent Services, including (but not limited to):</span></p>
                <ul>
                    <li>identification and authentication;</li>
                    <li>to protect Atricent and the users of the Site;</li>
                    <li>to customize the content and any advertising displayed on the Site;</li>
                    <li>to provide, maintain, protect and improve our services;</li>
                    <li>providing your information to a user with whom you have or had a contract facilitated by Atricent;</li>
                    <li>as required by law, an order of a court, tribunal or regulator or if Atricent reasonably believes that the use or disclosure of the information is reasonably necessary for enforcement related activities;</li>
                    <li>to develop new service features;</li>
                    <li>to ensure that Atricent receives payment of the fees due to it;</li>
                    <li>to contact you (for example, to inform you about upcoming changes or improvements to our services);</li>
                    <li>to conduct research;</li>
                    <li>to permit content on the Site (such as postings or third party advertisements) to be targeted, on an aggregate basis, to the users for whom it is most likely to be relevant;</li>
                    <li>to expand our user base;</li>
                    <li>to develop our relationships with affiliate service providers;</li>
                    <li>to provide or arrange internal or external verification services obtained by you via the Site; and</li>
                    <li>to generate data reports on an aggregated, non-personally identifiable basis, for both internal and third party use, but subject to any applicable laws (for example, We may show advertisers or investors trends relating to the general use of Atricent's services).</li>
                </ul>
                <p><span>Your contact information may also be used for accounting, invoicing and billing purposes, marketing purposes, by third party service providers to Atricent, and to respond to any inquiry you make, in some cases information we collect is transferred overseas. When you contact Atricent, We may keep a record of the communication(s) between you and Atricent to help resolve any issues you might have. If other user(s) of the Site already have your user ID (or other information identifying you), and you have chosen to upload a photo or other personal information to your Atricent account, We may show those user(s) that personal information.</span></p>
                <p><span>In certain circumstances We will use your email address to administer our User Agreement (for example, We may notify you of a breach, or action a request for a Take Down Notice in response to a claim of copyright infringement).</span></p>
                <p><span>If We collect, use or disclose any information from you that is not personal information, but is sensitive information (such as information relating to police checks conducted on users of the Site), then We will seek consent directly from you each time we collect, use or disclose your sensitive information, including for direct marketing purposes. We will not use or disclose your sensitive information for any other purpose unless the purpose is directly related to the primary purpose for which your sensitive information was collected.</span></p>
                <h3><span>2. Cookies and Anonymous Identifiers</span></h3>
                <p><span>If you have registered on the Site then your computer or device may store an identifying cookie or anonymous identifier, which can save you time each time you re-visit the Site, by accessing your information when you sign-in to Atricent.</span></p>
                <p><span>Atricent may use cookies and anonymous identifiers for a number of purposes including to access your information when you sign in, keep track of your preferences, direct specific content to you, report on Atricent's user base, and to improve Atricent's services. We may also use cookies or anonymous identifiers when you interact with our affiliate service providers (for example, when you integrate your Atricent account with your Facebook profile).</span></p>
                <p><span>You agree that if you change the settings on your internet browser to block or restrict cookies (including cookies associated with Atricent's services), or to indicate when a cookie is being set by Atricent, the Atricent Services may not work as intended. You should remember that, while you may still be able to use the Site if your cookies are disabled, our services may not function properly on your device and you may not be able to take advantage of certain Atricent features.</span></p>
                <h3><span>3. Protecting and Maintaining Personal Information</span></h3>
                <p><span>Your account is protected by a password for your privacy and security. We will take all reasonable steps to protect the information We hold about you from unauthorized access, use, and disclosure, however, We cannot guarantee the absolute security of that information, or that our systems will be completely free from third party interception or are incorruptible from viruses. We cannot and do not guarantee that information you send from your computer to us over the Internet will be protected by any form of encryption (encoding software). In light of this, We cannot and do not ensure or warrant the security or privacy of your personal information, including payment and account details. You transmit your personal information to us at your own risk.</span></p>
                <p><span>You are entirely responsible for maintaining the security of your passwords and/or account information.</span></p>
                <h3><span>4. Third Parties</span></h3>
                <p><span>The Site may contain links to third party websites including the networks of our valued affiliate service providers, advertisers, and Payment gateways, or make available services obtained from third parties, including verification services by third-party verification providers. If you follow a link to any of these websites, for instance using any third party payment system, or use any services obtained from third-party service providers via the Site that requires you to provide personal information (including sensitive information if relevant) directly to such third parties (for instance third party verification providers), note that they have their own privacy policies. If you use our Site to link to another site, or use a service obtained from a third party service provider via the Site, you will be subject to that site's or third party's terms and conditions of use, privacy policy and security statement. We strongly encourage you to view these before disclosing any of your personal information on such sites.</span></p>
                <p><span>Atricent does not control, and does not accept any responsibility or liability for, the privacy policy of, and use of personal information by, any party other than Atricent, including any user of the Site, the operators of any website to which the Site links, or third party service providers to whom you directly provide your personal information (including sensitive information if relevant) to.</span></p>
                <p><span>If Atricent is involved in a merger, acquisition or asset sale, We will give affected users of the Site notice before their personal information is transferred to another entity or becomes subject to a different privacy policy.</span></p>
                <p><span>Third-party vendors, including Google, may show Atricent ads on sites across the Internet. The Atricent website and Mobile Apps make use of the Google Maps API to assist with location based information. More information about the Google Maps API and the related privacy policy can be found here http://www.google.com/privacy.html</span></p>
                <p><span>For the avoidance of doubt, if you use any verification services made available by Atricent via its Site, that is not performed by Atricent but a third party verification provider, then any personal information (including sensitive information if relevant) that you provide as required by that third party in order to perform its verification services, will be collected directly by the relevant third party verification provider and will not be collected, handled, stored or otherwise used by Atricent. Atricent will only receive your verification status from the third party verification provider (for example, 'granted' or 'not granted' or such other like status) in order to issue any relevant Verification Badge on the Site. The use and handling of personal information (including sensitive information if relevant) remain the responsibility of the third party verification provider under its own privacy policy.</span></p>
                <h3><span>5. Marketing</span></h3>
                <p><span>When you register on the Site you may get various emails and SMS about our latest services, news, and special offers, and those of our valued affiliate service providers ("Marketing Material"), via your Atricent account, personal e-mail address, post or telephone. If you conclude a transaction on the Site, you may also receive Marketing Material from Atricent and our valued affiliate service providers.</span></p>
                <p><span>For our promotional emails, you can opt-out our emails anytime by simply clicking on to the unsubscribe button beneath the email body that you have received.</span></p>
                <p><span>Atricent may contact you as the result of a referral by another user of the Site who has provided us with contact information, such as your name and email address. The use of contact information received in connection with a referral will be governed by this Privacy Policy.</span></p>
                <p><span>Atricent uses Remarketing with Google Analytics to advertise online. Using the Ads Settings in a personal Google account, visitors can opt-out of Google Analytics for Display Advertising and customize Google Display Network ads.</span></p>
                <p><span>Marketing Atricent and third-party vendors, including Google, use first-party cookies (such as the Google Analytics cookie) and third-party cookies (such as the DoubleClick cookie) together to inform, optimize, and serve ads based on someone's past visits to the Atricent website.</span></p>
                <p><span>Using the Ads Settings in a personal Google account, visitors can opt-out of Google Analytics for Display Advertising and customize Google Display Network ads.</span></p>
                <h3><span>6. Administrative Communications</span></h3>
                <p><span>Atricent reserves the right to send you administrative and account-related messages that you may not opt-out of. To cease all communications to you from Atricent you must close down your Atricent account.</span></p>
                <h3><span>7. Accessing Personal Information</span></h3>
                <p><span>We will allow you, at any time, to access, edit, update and/ or delete the personal information that We hold about you, unless:</span></p>
                <p><span>We are legally permitted or required to deny you access to, and/ or to retain, the information; or you make request(s) that are unreasonably repetitive, require Atricent to make a disproportionate technical effort (for example, to develop an entirely new system), risk the privacy of others, or would be highly impractical to comply with.</span></p>
                <p><span>If you wish to access the personal information We hold about you, or to delete your Atricent account, you should contact us here.</span></p>
                <p><span>We need to prevent information in our systems from being accidentally or maliciously destroyed. This means that, where you delete information from our services, residual copies of that information on our active servers, as well as any corresponding information on our back-up systems, may not be immediately deleted.</span></p>
                <h3><span>8. Privacy Concerns</span></h3>
                <p><span>If you have concerns about how We handle your personal information or require further information, please email Atricent using the contact form provided on the Site. If you make a formal written complaint in relation to our compliance with this Privacy Policy, We will contact you to follow up on that complaint. Other than material that you voluntarily choose to post on the Site (such as Sender postings, bids and comments on other users), the only information about you that We will post publicly is your Atricent public profile.</span></p>
                <p><span>Atricent may, from time to time, modify this Privacy Policy (and update the web page on which it is displayed). Atricent will send notification of any such modification to your Atricent account and/or your registered email address. You should check that account regularly.</span></p>
                <h3><span>9. Delivery policy</span></h3>
                <p>Atricent partner arrived on the task location in hour from booking time.</p>
                <p class="MsoNormal"><span lang="EN-US">&nbsp;</span></p>
            </div>
        </div>
    )
}

export default PrivacyPolicy